# Generated by Django 6.1.1 on 2026-09-09 16:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("bronce", "Bronce"),
                            ("plata", "Plata"),
                            ("oro", "Oro"),
                            ("platino", "Platino"),
                            ("diamante", "Diamante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requisitos", models.JSONField(default=dict)),
                ("imagen", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContenidoJSON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("archivo", models.CharField(max_length=300)),
                ("datos", models.JSONField(default=dict)),
                ("categoria", models.CharField(blank=True, max_length=200, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contenido JSON",
                "verbose_name_plural": "Contenidos JSON",
            },
        ),
        migrations.CreateModel(
            name="EjercicioLinguistico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "contenido",
                    models.JSONField(default=dict, verbose_name="Contenido completo"),
                ),
                ("categoria", models.CharField(blank=True, max_length=200, null=True)),
                ("tipo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nivel",
                    models.IntegerField(default=1, help_text="Nivel de dificultad"),
                ),
                ("puntos", models.IntegerField(default=10)),
                (
                    "archivo_origen",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ejercicio Lingüístico",
                "verbose_name_plural": "Ejercicios Lingüísticos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diagnostico", "Diagnóstico"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                ("categoria", models.CharField(max_length=100)),
                ("nivel_requerido", models.IntegerField(default=1)),
                ("puntos_base", models.IntegerField(default=10)),
                ("duracion_minutos", models.IntegerField(default=30)),
                ("preguntas", models.JSONField(default=list)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Logro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("insignia", "Insignia"),
                            ("medalla", "Medalla"),
                            ("estrella", "Estrella"),
                            ("certificacion", "Certificación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        help_text="Clase de Font Awesome o emoji", max_length=100
                    ),
                ),
                ("color", models.CharField(default="gold", max_length=50)),
                ("puntos_requeridos", models.IntegerField(default=0)),
                ("nivel_requerido", models.IntegerField(default=1)),
                (
                    "categoria_requerida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ejercicios_completados_requeridos", models.IntegerField(default=0)),
                ("tasa_aciertos_requerida", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="TecnicaLinguistica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(blank=True, max_length=200, null=True)),
                ("nivel", models.IntegerField(default=1)),
                (
                    "archivo_origen",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Técnica Lingüística",
                "verbose_name_plural": "Técnicas Lingüísticas",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("nivel", models.CharField(default="Aprendiz", max_length=20)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "estrellas",
                    models.IntegerField(
                        default=0, help_text="Estrellas de oro acumuladas"
                    ),
                ),
                (
                    "medallas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de medallas obtenidas",
                    ),
                ),
                (
                    "insignias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de insignias obtenidas",
                    ),
                ),
                (
                    "certificaciones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de certificaciones obtenidas",
                    ),
                ),
                (
                    "racha",
                    models.IntegerField(
                        default=0, help_text="Días consecutivos practicando"
                    ),
                ),
                ("ultima_actividad", models.DateTimeField(blank=True, null=True)),
                ("total_ejercicios_completados", models.IntegerField(default=0)),
                ("tasa_aciertos", models.FloatField(default=0.0)),
                ("nivel_experiencia", models.IntegerField(default=1)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="core_user_set",
                        related_query_name="core_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="core_user_set",
                        related_query_name="core_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.IntegerField(default=0)),
                ("respuestas", models.JSONField(default=list)),
                ("tiempo_utilizado", models.IntegerField(default=0)),
                ("completada", models.BooleanField(default=False)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "calificacion",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("feedback_general", models.TextField(blank=True, null=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.evaluacion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_ejercicio", models.CharField(max_length=50)),
                ("item_id", models.IntegerField()),
                ("respuesta_usuario", models.TextField()),
                ("es_correcta", models.BooleanField(default=False)),
                ("puntuacion", models.IntegerField(default=0)),
                (
                    "tiempo_segundos",
                    models.IntegerField(default=0, help_text="Tiempo en segundos"),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("intento_numero", models.IntegerField(default=1)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgresoCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=100)),
                ("aciertos", models.IntegerField(default=0)),
                ("intentos", models.IntegerField(default=0)),
                (
                    "nivel_dominio",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("estrellas_obtenidas", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogroObtenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_obtenida", models.DateTimeField(auto_now_add=True)),
                ("notificado", models.BooleanField(default=False)),
                (
                    "logro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.logro"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logros_obtenidos",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificacionObtenida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_obtenida", models.DateTimeField(auto_now_add=True)),
                ("codigo_verificacion", models.CharField(max_length=100, unique=True)),
                ("url_verificacion", models.URLField(blank=True, null=True)),
                (
                    "certificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.certificacion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones_obtenidas",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
