# Generated by Django 6.1.1 on 2026-09-09 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaGenerada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("correccion", "Corrección"),
                            ("completar", "Completar"),
                            ("reescribir", "Reescribir"),
                            ("elegir", "Elegir"),
                            ("explicar", "Explicar"),
                            ("verdadero_falso", "Verdadero/Falso"),
                            ("relacionar", "Relacionar"),
                            ("ordenar", "Ordenar"),
                            ("multiple_choice", "Opción Múltiple"),
                            ("desarrollo", "Desarrollo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("enunciado", models.TextField()),
                ("respuesta_correcta", models.TextField()),
                ("opciones", models.JSONField(blank=True, null=True)),
                ("pista", models.TextField(blank=True)),
                (
                    "dificultad",
                    models.IntegerField(
                        choices=[
                            (1, "Principiante"),
                            (2, "Intermedio"),
                            (3, "Avanzado"),
                            (4, "Experto"),
                        ],
                        default=1,
                    ),
                ),
                ("puntos", models.IntegerField(default=10)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("ejercicio_base_id", models.IntegerField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(default=django.utils.timezone.now)),
                ("usado_en", models.IntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.TextField()),
                ("es_correcta", models.BooleanField(default=False)),
                ("puntos_obtenidos", models.IntegerField(default=0)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("tiempo_respuesta", models.IntegerField(blank=True, null=True)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.preguntagenerada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="preguntagenerada",
            index=models.Index(
                fields=["tipo", "dificultad"], name="core_pregun_tipo_41707c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preguntagenerada",
            index=models.Index(fields=["activa"], name="core_pregun_activa_25b7a9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="respuestapregunta",
            unique_together={("pregunta", "usuario")},
        ),
    ]
