# Generated by Django 6.1.1 on 2026-09-09 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_preguntagenerada_respuestapregunta_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("descripcion", models.TextField()),
                ("objetivo", models.TextField(blank=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("principiante", "Principiante"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                            ("experto", "Experto"),
                        ],
                        default="principiante",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicado", "Publicado"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "duracion_estimada",
                    models.IntegerField(
                        default=10, help_text="Duración estimada en horas"
                    ),
                ),
                ("puntos_totales", models.IntegerField(default=0)),
                ("creado_en", models.DateTimeField(default=django.utils.timezone.now)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("publicado_en", models.DateTimeField(blank=True, null=True)),
                ("estudiantes_inscritos", models.IntegerField(default=0)),
                ("calificacion_promedio", models.FloatField(default=0.0)),
                ("numero_revisiones", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("teoria", "Teoría"),
                            ("practica", "Práctica"),
                            ("evaluacion", "Evaluación"),
                            ("mixto", "Mixto"),
                        ],
                        default="teoria",
                        max_length=20,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "duracion_estimada",
                    models.IntegerField(default=15, help_text="Duración en minutos"),
                ),
                ("puntos", models.IntegerField(default=10)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.IntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("puntaje_obtenido", models.IntegerField(default=0)),
                ("intentos", models.IntegerField(default=0)),
                (
                    "tiempo_dedicado",
                    models.IntegerField(default=0, help_text="Tiempo en segundos"),
                ),
                (
                    "ultima_actividad",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completado_en", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="preguntagenerada",
            name="core_pregun_tipo_41707c_idx",
        ),
        migrations.RemoveIndex(
            model_name="preguntagenerada",
            name="core_pregun_activa_25b7a9_idx",
        ),
        migrations.AddField(
            model_name="curso",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="tecnicas_relacionadas",
            field=models.ManyToManyField(blank=True, to="core.tecnicalinguistica"),
        ),
        migrations.AddField(
            model_name="leccion",
            name="ejercicios_relacionados",
            field=models.ManyToManyField(blank=True, to="core.ejerciciolinguistico"),
        ),
        migrations.AddField(
            model_name="leccion",
            name="tecnicas_relacionadas",
            field=models.ManyToManyField(blank=True, to="core.tecnicalinguistica"),
        ),
        migrations.AddField(
            model_name="modulo",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modulos",
                to="core.curso",
            ),
        ),
        migrations.AddField(
            model_name="leccion",
            name="modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecciones",
                to="core.modulo",
            ),
        ),
        migrations.AddField(
            model_name="progresousuario",
            name="leccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresos",
                to="core.leccion",
            ),
        ),
        migrations.AddField(
            model_name="progresousuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_lecciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="preguntagenerada",
            name="creado_por",
        ),
        migrations.DeleteModel(
            name="RespuestaPregunta",
        ),
        migrations.AlterUniqueTogether(
            name="modulo",
            unique_together={("curso", "orden")},
        ),
        migrations.AlterUniqueTogether(
            name="leccion",
            unique_together={("modulo", "orden")},
        ),
        migrations.AlterUniqueTogether(
            name="progresousuario",
            unique_together={("usuario", "leccion")},
        ),
        migrations.DeleteModel(
            name="PreguntaGenerada",
        ),
    ]
