# Generated by Django 6.1.1 on 2026-09-09 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_curso_leccion_modulo_progresousuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluacionCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diagnostica", "Diagnóstica"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                            ("final", "Final"),
                        ],
                        default="formativa",
                        max_length=20,
                    ),
                ),
                ("preguntas_por_evaluacion", models.IntegerField(default=10)),
                (
                    "tiempo_limite",
                    models.IntegerField(default=30, help_text="Tiempo en minutos"),
                ),
                ("puntaje_maximo", models.IntegerField(default=100)),
                ("intentos_permitidos", models.IntegerField(default=3)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("disponible_desde", models.DateTimeField(blank=True, null=True)),
                ("disponible_hasta", models.DateTimeField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="core.curso",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="core.modulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("multiple", "Opción Múltiple"),
                            ("verdadero_falso", "Verdadero/Falso"),
                            ("completar", "Completar"),
                            ("desarrollo", "Desarrollo"),
                            ("correccion", "Corrección"),
                        ],
                        default="multiple",
                        max_length=20,
                    ),
                ),
                ("opciones", models.JSONField(blank=True, null=True)),
                ("respuesta_correcta", models.TextField()),
                ("puntaje", models.IntegerField(default=10)),
                ("orden", models.IntegerField(default=0)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ejerciciolinguistico",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="core.evaluacioncurso",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoEvaluacionCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_obtenido", models.IntegerField(default=0)),
                ("puntaje_maximo", models.IntegerField(default=0)),
                ("respuestas", models.JSONField(default=dict)),
                ("intento", models.IntegerField(default=1)),
                ("completado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                (
                    "tiempo_empleado",
                    models.IntegerField(default=0, help_text="Tiempo en segundos"),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="core.evaluacioncurso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_evaluaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("evaluacion", "usuario", "intento")},
            },
        ),
    ]
